package com.tarkalabs.tarkaui.theme

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

@Immutable
open class TUIColors(
  val primary: Color,
  val onPrimary: Color,
  val primaryAlt: Color,
  val onPrimaryAlt: Color,
  val secondary: Color,
  val onSecondary: Color,
  val secondaryAlt: Color,
  val onSecondaryAlt: Color,
  val tertiary: Color,
  val onTertiary: Color,
  val tertiaryAlt: Color,
  val onTertiaryAlt: Color,
  val success: Color,
  val onSuccess: Color,
  val success10: Color,
  val success20: Color,
  val error: Color,
  val onError: Color,
  val error55: Color,
  val error10: Color,
  val warning: Color,
  val onWarning: Color,
  val warning10: Color,
  val background: Color,
  val onBackground: Color,
  val utilityOutline: Color,
  val utilityDisabledContent: Color,
  val utilityDisabledBackground: Color,
  val utilityLink: Color,
  val inputBackground: Color,
  val inputText: Color,
  val inputDim: Color,
  val surface: Color,
  val surface50: Color,
  val onSurface: Color,
  val surfaceVariant: Color,
  val surfaceVariantHover: Color,
  val constantLight: Color,
  val constantDark: Color,
  val inputTextDim: Color,
  val surfaceHover: Color,
  val primaryAltHover: Color,
  val accent: Color,
  val accentBaseA: Color,
  val accentBaseB: Color,
  val accentBaseC: Color,
  val accentBaseD: Color,
  val accentBaseE: Color,
  val accentBaseF: Color,
  val accentBaseG: Color,
  val accentBaseH: Color,
  val accentBaseI: Color,
  val accentBaseJ: Color,
  val accentBaseK: Color,
  val accentBaseL: Color,
  val accentBaseM: Color,
  val accentBaseN: Color,
  val accentBaseO: Color,
  val accentBaseP: Color,
  val accentBaseQ: Color,
  val accentBaseR: Color,
  val onAccent: Color,
  val onAccentA: Color,
  val onAccentB: Color,
  val onAccentC: Color,
  val onAccentD: Color,
  val onAccentE: Color,
  val onAccentF: Color,
  val onAccentG: Color,
  val onAccentH: Color,
  val onAccentI: Color,
  val onAccentJ: Color,
  val onAccentK: Color,
  val onAccentL: Color,
  val onAccentM: Color,
  val onAccentN: Color,
  val onAccentO: Color,
  val onAccentP: Color,
  val onAccentQ: Color,
  val onAccentR: Color
)
val LocalTUIColors = staticCompositionLocalOf {
  defaultLightColors
}

val defaultLightColors = TUIColors(
  primary = Color(0xFF0052D6),
  onPrimary = Color(0xFFF5F9FF),
  primaryAlt = Color(0xFFD5E2F6),
  onPrimaryAlt = Color(0xFF002766),
  secondary = Color(0xFF4D80B3),
  onSecondary = Color(0xFFF0F7FF),
  secondaryAlt = Color(0xFFD2DEE9),
  onSecondaryAlt = Color(0xFF003366),
  tertiary = Color(0xFF924F92),
  onTertiary = Color(0xFFFFF5FF),
  tertiaryAlt = Color(0xFFF3CEF3),
  onTertiaryAlt = Color(0xFF530953),
  success = Color(0xFF148F47),
  onSuccess = Color(0xFFF2FDF6),
  success10 = Color(0xFF148F47).copy(alpha = 0.10f),
  success20 = Color(0xFF148F47).copy(alpha = 0.20f),
  error = Color(0xFFCD1D32),
  error55 = Color(0xFFCD1D32).copy(alpha = 0.55f),
  onError = Color(0xFFFEFBFB),
  error10 = Color(0xFFCD1D32).copy(alpha = 0.10f),
  warning = Color(0xFFFFB938),
  onWarning = Color(0xFF241D0F),
  warning10 = Color(0xFF241D0F).copy(alpha = 0.10f),
  background = Color(0xFFECECEC),
  onBackground = Color(0xFF171B21),
  utilityOutline = Color(0xFF878B92),
  utilityDisabledContent = Color(0XFF1A1B1F).copy(alpha = 0.38f),
  utilityDisabledBackground = Color(0XFF1A1B1F).copy(alpha = 0.06f),
  utilityLink = Color(0xFF3381FF),
  inputBackground = Color(0XFFEAEDF0).copy(alpha = 0.85f),
  inputText = Color(0XFF1A1B1F),
  inputDim = Color(0XFF1A1B1F).copy(alpha = 0.70f),
  surface = Color(0xFFF9FAFB),
  surface50 = Color(0xFFF9FAFB).copy(alpha = 0.50f),
  onSurface = Color(0xFF1A1B1F),
  surfaceVariant = Color(0xFFEBEFF4),
  constantLight = Color(0xFFFFFFFF),
  constantDark = Color(0xFF000000),
  surfaceVariantHover = Color(0xFFE1E7EF),
  inputTextDim = Color(0xFF1A1C1F),
  surfaceHover = Color(0xFFF0F2F5),
  primaryAltHover = Color(0xFFC4D7F3),
  accent = Color(0xFFE8DEED),
  accentBaseA = Color(0xFFEDDEDE),
  accentBaseB = Color(0xFFEDE3DE),
  accentBaseC = Color(0xFFEDE8DE),
  accentBaseD = Color(0xFFEDEDDE),
  accentBaseE = Color(0xFFE8EDDE),
  accentBaseF = Color(0XFFE3EDDE),
  accentBaseG = Color(0xFFDEEDDE),
  accentBaseH = Color(0xFFDEEDE3),
  accentBaseI = Color(0xFFDEEDE8),
  accentBaseJ = Color(0xFFDEEDED),
  accentBaseK = Color(0XFFDEE8ED),
  accentBaseL = Color(0xFFDEE3ED),
  accentBaseM = Color(0xFFDEDEED),
  accentBaseN = Color(0xFFE3DEED),
  accentBaseO = Color(0xFFE8DEED),
  accentBaseP = Color(0XFFEDDEED),
  accentBaseQ = Color(0xFFEDDEE8),
  accentBaseR = Color(0xFFEDDEE3),
  onAccent = Color(0xFF5F008F),
  onAccentA = Color(0xFF8F0000),
  onAccentB = Color(0xFF8F3000),
  onAccentC = Color(0xFF8F5F00),
  onAccentD = Color(0xFF8F8F00),
  onAccentE = Color(0xFF5F8F00),
  onAccentF = Color(0XFF308F00),
  onAccentG = Color(0xFF008F00),
  onAccentH = Color(0xFF008F30),
  onAccentI = Color(0xFF008F5F),
  onAccentJ = Color(0xFF008F8F),
  onAccentK = Color(0XFF005F8F),
  onAccentL = Color(0xFF00308F),
  onAccentM = Color(0xFF00008F),
  onAccentN = Color(0xFF30008F),
  onAccentO = Color(0xFF5F008F),
  onAccentP = Color(0XFF8F008F),
  onAccentQ = Color(0xFF8F005F),
  onAccentR = Color(0xFF8F0030)
)

val defaultDarkColors = TUIColors(
  primary = Color(0xFF5294FF),
  onPrimary = Color(0xFFFAFCFF),
  primaryAlt = Color(0xFF293B56),
  onPrimaryAlt = Color(0xFFD6E6FF),
  secondary = Color(0xFFA8CCF0),
  onSecondary = Color(0xFF002B57),
  secondaryAlt = Color(0xFF294056),
  onSecondaryAlt = Color(0xFFD6EBFF),
  tertiary = Color(0xFFE6B3E6),
  onTertiary = Color(0xFF5C0A5C),
  tertiaryAlt = Color(0xFF532D53),
  onTertiaryAlt = Color(0xFFFFD6FF),
  success = Color(0xFF55E792),
  onSuccess = Color(0xFF003817),
  success10 = Color(0xFF55E792).copy(alpha = 0.10f),
  success20 = Color(0xFF55E792).copy(alpha = 0.20f),
  error = Color(0xFFD42136),
  error55 = Color(0xFFD42136).copy(alpha = 0.55f),
  onError = Color(0xFFFFFAFA),
  error10 = Color(0xFFD42136).copy(alpha = 0.10f),
  warning = Color(0xFFFFB938),
  onWarning = Color(0xFF241D0F),
  warning10 = Color(0xFF241D0F).copy(alpha = 0.10f),
  background = Color(0xFF0F1115),
  onBackground = Color(0xFFF0F2F4),
  utilityOutline = Color(0xFF878B92),
  utilityDisabledContent = Color(0XFFFCFCFD).copy(alpha = 0.38f),
  utilityDisabledBackground = Color(0XFFFCFCFD).copy(alpha = 0.12f),
  utilityLink = Color(0xFF80B0FF),
  inputBackground = Color(0XFF0F1115).copy(alpha = 0.85f),
  inputText = Color(0XFFFCFCFD),
  inputDim = Color(0XFFFCFCFD).copy(alpha = 0.70f),
  surface = Color(0xFF212731),
  surface50 = Color(0xFF212731).copy(alpha = 0.50f),
  onSurface = Color(0xFFFCFCFD),
  surfaceVariant = Color(0xFF2D3543),
  constantLight = Color(0xFFFFFFFF),
  constantDark = Color(0xFF000000),
  surfaceVariantHover = Color(0xFF353F50),
  inputTextDim = Color(0xFFFCFCFD),
  surfaceHover = Color(0xFF29313D),
  primaryAltHover = Color(0xFF324767),
  accent = Color(0xFF32203C),
  accentBaseA = Color(0xFF3C2020),
  accentBaseB = Color(0xFF3C2920),
  accentBaseC = Color(0xFF3C3220),
  accentBaseD = Color(0xFF3C3C20),
  accentBaseE = Color(0xFF323C20),
  accentBaseF = Color(0XFF293C20),
  accentBaseG = Color(0xFF203C20),
  accentBaseH = Color(0xFF203C29),
  accentBaseI = Color(0xFF203C32),
  accentBaseJ = Color(0xFF203C3C),
  accentBaseK = Color(0XFF20323C),
  accentBaseL = Color(0xFF20293C),
  accentBaseM = Color(0xFF20203C),
  accentBaseN = Color(0xFF29203C),
  accentBaseO = Color(0xFF32203C),
  accentBaseP = Color(0XFF3C203C),
  accentBaseQ = Color(0xFF3C2032),
  accentBaseR = Color(0xFF3C2029),
  onAccent = Color(0xFFDD99FF),
  onAccentA = Color(0xFFFF9999),
  onAccentB = Color(0xFFFFBB99),
  onAccentC = Color(0xFFFFDD99),
  onAccentD = Color(0xFFFFFF99),
  onAccentE = Color(0xFFDDFF99),
  onAccentF = Color(0XFFBBFF99),
  onAccentG = Color(0xFF99FF99),
  onAccentH = Color(0xFF99FFBB),
  onAccentI = Color(0xFF99FFDD),
  onAccentJ = Color(0xFF99FFFF),
  onAccentK = Color(0XFF99DDFF),
  onAccentL = Color(0xFF99BBFF),
  onAccentM = Color(0xFF9999FF),
  onAccentN = Color(0xFFBB99FF),
  onAccentO = Color(0xFFDD99FF),
  onAccentP = Color(0XFFFF99FF),
  onAccentQ = Color(0xFFFF99DD),
  onAccentR = Color(0xFFFF99BB)
)