package com.tarkalabs.uicomponents

object Tags {

  const val TAG_TEXT_ROW = "text_row_item"
  const val TAG_TEXT_ROW_INFO_ICON = "text_row_info_icon_item"
  const val TAG_TEXT_ROW_ICON_ONE = "text_row_icon_one_item"
  const val TAG_TEXT_ROW_ICON_TWO = "text_row_icon_two_item"
  const val TAG_TEXT_ROW_BUTTON = "text_row_button_item"
  const val TAG_TOGGLE_SWITCH = "toggle_switch_item"
  const val TAG_TOGGLE_SWITCH_ICON = "toggle_switch_icon_item"
  const val TAG_ICON_BUTTON = "icon_button_item"
  const val TAG_BADGE = "badge_item"
  const val TAG_BUTTON = "button_item"
  const val TAG_BUTTON_LEADING_ICON = "button_leading_icon"
  const val TAG_BUTTON_TRAILING_ICON = "button_trailing_icon"
  const val TAG_NAVIGATION_ROW = "navigation_row"
  const val TAG_NAVIGATION_ROW_LEADING_ICON = "navigation_row_leading_icon"
  const val TAG_NAVIGATION_ROW_RIGHT_ARROW = "navigation_row_right_arrow"
  const val TAG_FAB = "floating_action_button_item"
  const val TAG_STATUS_INDICATOR = "status_indicator"
  const val TAG_STATUS_INDICATOR_CIRCLE = "status_indicator_circle"
  const val TAG_AVATAR = "tag_avatar"
  const val TAG_AVATAR_BADGE = "tag_avatar_badge"
  const val TAG_SNACK_BAR = "tag_snack_bar"
  const val TAG_SNACK_BAR_LEADING_ICON = "snack_bar_leading_icon"
  const val TAG_SNACK_BAR_DISMISS_ACTION = "snack_bar_dismiss_action"
  const val TAG_CHECK_BOX = "check_box"
  const val TAG_CHECK_BOX_ROW = "check_box_row"
  const val TAG_SEARCH_BAR = "search_bar"
  const val TAG_CHIP_TAG = "tui_chip"
  const val TAG_RADIO_BUTTON = "radio_button"
  const val TAG_RADIO_BUTTON_ROW = "radio_button_row"

}