package com.tarkalabs.uicomponents

object Tags {
  const val TAG_TEXT_ROW = "text_row_item"
  const val TAG_TEXT_ROW_INFO_ICON = "text_row_info_icon_item"
  const val TAG_TEXT_ROW_BUTTON = "text_row_button_item"
  const val TAG_TOGGLE_SWITCH = "toggle_switch_item"
  const val TAG_TOGGLE_SWITCH_ICON = "toggle_switch_icon_item"
  const val TAG_ICON_BUTTON = "icon_button_item"
  const val TAG_ICON_BUTTON_ICON = "icon_button_icon"
  const val TAG_BADGE = "badge_item"
  const val TAG_BUTTON = "button_item"
  const val TAG_BUTTON_LEADING_ICON = "button_leading_icon"
  const val TAG_BUTTON_TRAILING_ICON = "button_trailing_icon"
  const val TAG_NAVIGATION_ROW_BADGE = "navigation_row_badge"
  const val TAG_NAVIGATION_ROW = "navigation_row"
  const val TAG_NAVIGATION_ROW_LEADING_ICON = "navigation_row_leading_icon"
  const val TAG_NAVIGATION_ROW_TEXT = "navigation_row_text"
  const val TAG_FAB = "floating_action_button_item"
  const val TAG_FAB_ICON = "floating_action_button_icon_item"
  const val TAG_THEME = "theme"
  const val TAG_STATUS_INDICATOR = "status_indicator"
  const val TAG_STATUS_INDICATOR_CIRCLE = "status_indicator_circle"
  const val TAG_AVATAR = "tag_avatar"
  const val TAG_AVATAR_BADGE = "tag_avatar_badge"
}