name: Commits and Pull Requests
on:
  on:
    workflow_dispatch:
    push:
    pull_request_target:
      types: [ synchronize, ready_for_review ]
    pull_request:
      types: [ opened ]

jobs:
  build:
    name: Building
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Build
        run: bash ./gradlew build
  screenshot-test:
    name: Run Screenshot tests
    runs-on: macos-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Make files executable
        run: chmod +x ./gradlew
      - name: Screenshot tests
        uses: reactivecircus/android-emulator-runner@v2.24.0
        with:
          api-level: 31
          arch: x86_64
          profile: pixel
          target: google_apis
          sdcard-path-or-size: 512M
          emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim
          script: ./gradlew executeScreenshotTests