name: ScreenShot Testing
on:
    workflow_dispatch:
    push:
    pull_request_target:
      types: [ synchronize, ready_for_review ]
    pull_request:
      types: [ opened ]

jobs:

  screenshot-test:
    name: Run Screenshot tests
    runs-on: macos-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Make files executable
        run: chmod +x ./gradlew
      - name: Screenshot tests
        uses: reactivecircus/android-emulator-runner@v2.24.0
        with:
          api-level: 32
          arch: x86_64
          profile: pixel_4
          target: google_apis
          sdcard-path-or-size: 512M
          disable-animations: true
          emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim
          script: ./gradlew executeScreenshotTests
      - name: Upload Screenshot Results
        if : always()
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: '**/tarkaui/build/reports/shot/debug/'